//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopmentChallenge.Infrastructure.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Textos {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Textos() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevelopmentChallenge.Infrastructure.Resources.Textos", typeof(Textos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Círculo.
        /// </summary>
        internal static string CirculoSingular {
            get {
                return ResourceManager.GetString("CirculoSingular", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Círculos.
        /// </summary>
        internal static string CirculoPlural {
            get {
                return ResourceManager.GetString("CirculoPlural", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cuadrado.
        /// </summary>
        internal static string CuadradoSingular {
            get {
                return ResourceManager.GetString("CuadradoSingular", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cuadrados.
        /// </summary>
        internal static string CuadradoPlural {
            get {
                return ResourceManager.GetString("CuadradoPlural", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to formas.
        /// </summary>
        internal static string Formas {
            get {
                return ResourceManager.GetString("Formas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Lista vacía de formas!&lt;/h1&gt;.
        /// </summary>
        internal static string ListaVacia {
            get {
                return ResourceManager.GetString("ListaVacia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Perimetro.
        /// </summary>
        internal static string Perimetro {
            get {
                return ResourceManager.GetString("Perimetro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Reporte de Formas&lt;/h1&gt;.
        /// </summary>
        internal static string ReporteHeader {
            get {
                return ResourceManager.GetString("ReporteHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Trapecio.
        /// </summary>
        internal static string TrapecioSingular {
            get {
                return ResourceManager.GetString("TrapecioSingular", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Trapecios.
        /// </summary>
        internal static string TrapecioPlural {
            get {
                return ResourceManager.GetString("TrapecioPlural", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Triángulo.
        /// </summary>
        internal static string TrianguloSingular {
            get {
                return ResourceManager.GetString("TrianguloSingular", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Triángulos.
        /// </summary>
        internal static string TrianguloPlural {
            get {
                return ResourceManager.GetString("TrianguloPlural", resourceCulture);
            }
        }
    }
}
